version: 2.1

jobs:
  build:
    working_directory: ~/loki-dnd-repro
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - run: 
          name: Setup NVM
          command: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Update node
          command: |
            nvm install 18.16.0
      - run:
          name: Install and Update Dependencies
          command: |
            nvm use 18.16.0
            npm install -g npm
            npm install -g yarn
            yarn install
      - run:
          name: Build storybook
          command: |
            nvm use 18.16.0
            yarn build-storybook
      - run:
          name: Run visual test
          command: |
            nvm use 18.16.0
            yarn test:visual:ci

workflows:
  version: 2
  all:
    jobs:
      - build